# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1  # 3.0

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: zh

pipeline:
  - name: "MitieNLP"
    #model: "/home/fanzhimin/Downloads/total_word_feature_extractor_zh.dat"
    model: "C:\\Users\\Administrator\\mitie_model_and_vocab\\total_word_feature_extractor_zh.dat"
    #- name: "MitieTokenizer"
    #  "intent_tokenization_flag": False
    #  "intent_split_symbol": "_"
    #  "token_pattern": None
  - name: "JiebaTokenizer"
    #dictionary_path: "/home/fanzhimin/Downloads/dict.chn.txt.big.txt"
    dictionary_path: "C:\\Users\\Administrator\\mitie_model_and_vocab\\dict.chn.txt.big.txt"
    "intent_tokenization_flag": False
    "intent_split_symbol": "_"
    "token_pattern": None

  - name: "MitieFeaturizer"
    "pooling": "mean"

  #- name: "SpacyNLP"
  #    model: "zh_core_web_trf"
  #- name: "SpacyTokenizer"
  #    "intent_tokenization_flag": False
  #    "intent_split_symbol": "_"
  #    "token_pattern": None
  #- name: "SpacyFeaturizer"
  #    "pooling": "mean"

  # 抽取正则特征
  - name: "RegexFeaturizer"
    "case_sensitive": False        # 正则匹配中的大小写区分问题, False 是不区分
    "use_word_boundaries": False   # use match word boundaries for lookup table | 中文的情况这个参数就设置为 True，但是这里只是做 HTTP 英文实体抽取，所以这里设置为 False 是没问题的
    # fixme 保证正则特征的数量，这样做是在做增量训练时保证正则特征的有效性？同时涉及到一些增量训练问题，rasa 增量训练: https://rasa.com/docs/rasa/command-line-interface/#incremental-training
    number_additional_patterns: 10


  # fixme giikin bot 除了正则特征识别实体，还存在其它各种类型的商品 / 颜色 / 尺寸 / 地区 / 姓名 等各种其它类型的实体信息，
  # 根据正则抽取实体的配置说明，不需要这个组件，因此可以删除; 只是使用下面这个 MitieEntityExtractor 就可以完成实体抽取
  # 由于这里的数据除了 HTT 是借助 regex 进行抽取，其它商品实体都是纯模型识别，所以这里不用添加这个组件就可以完成基于 regex 的 HTTP 实体识别过程
  #- name: RegexEntityExtractor
  #  use_regexes: True
  #  case_sensitive: False
  #  use_lookup_tables: False
  #  use_word_boundaries: False # 中文的情况这个参数就设置为 True，涉及到一些分詞的操作 | 但是这里只是做 HTTP 英文实体抽取，所以这里设置为 False 是没问题的
  # MITIE NER trainer - 实体识别应该使用这个模型
  - name: "MitieEntityExtractor"


  # 用于意图分类和实体抽取 - 只配置该模型的话实体很难识别，需要配置下面这个实体模型
  - name: "DIETClassifier"
    epochs: 300
    entity_recognition: False          # 不进行实体识别;只进行意图分类
    # intent_classification: False     # 不进行意图分类;只进行实体识别

  #  - name: "SpacyEntityExtractor"
  #    dimensions: ["http_entity", "goods_entity"]


  # 分类 FAQ intents
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: faq


  - name: DucklingEntityExtractor
    url: "http://192.168.4.133:8000"
    dimensions: [ "phone" ]  # v.3.x
    #dimensions: # v.2.x
    #  - phone

  #  - name: FallbackClassifier
  #    threshold: 0.5                   # 满足 FallbackClassifier 回退可触发
  #    ambiguity_threshold: 0.3         # 满足 FallbackClassifier 回退可触发 | 两个意图之间的相似度触发回退的机制


policies:
  # # No configuration for policies was provided. The following default policies were used to train your model.
  # # If you'd like to customize them, uncomment and adjust the policies. / See https://rasa.com/docs/rasa/policies for more information.
  #   - name: UnexpecTEDIntentPolicy
  #     max_history: 5
  #     epochs: 100
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.5
    core_fallback_action_name: "utter_welcome_nothing"
    enable_fallback_prediction: True
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
